# Project language
language: python

sudo: false

dist: xenial

# Language versions to test against
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
  - nightly

matrix:
    fast_finish: true
    allow_failures:
        - python: nightly

# Install dependencies
install:
  - python setup.py -q install

# Run the unit test
script:
  - pytest
